"""Deterministic semantic color defaults for common urban map layers.

The resolver is intentionally conservative. It only replaces the known generic
Atlas palette generated by the Skill. User-authored colors are preserved.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, Iterable, Mapping, Optional, Sequence, Tuple

CATEGORICAL_PALETTE: Tuple[str, ...] = (
    "#4E8587",
    "#D39A4A",
    "#8C739B",
    "#C56E79",
    "#718F61",
    "#607F9D",
    "#A67D62",
    "#7C8588",
)

# Order matters. More specific roles must be checked before generic boundaries.
_SEMANTIC_KEYWORDS: Tuple[Tuple[str, Tuple[str, ...]], ...] = (
    (
        "water",
        (
            "water", "river", "stream", "creek", "canal", "pond", "lake",
            "wetland", "hydro", "水体", "水系", "河流", "河道", "溪流",
            "沟渠", "池塘", "湖泊", "湿地",
        ),
    ),
    (
        "parking",
        (
            "parking", "car park", "parking lot", "garage", "停车", "车位", "车库",
        ),
    ),
    (
        "green_space",
        (
            "green space", "greenspace", "park", "garden", "open space",
            "forest", "woodland", "grass", "公园", "绿地", "开放空间",
            "花园", "林地", "草地",
        ),
    ),
    (
        "commercial",
        (
            "commercial", "retail", "service facility", "amenity", "shop",
            "store", "market", "restaurant", "cafe", "商业", "服务设施",
            "零售", "商店", "餐饮", "市场",
        ),
    ),
    (
        "pedestrian",
        (
            "pedestrian", "footway", "footpath", "walkway", "walking",
            "steps", "path", "步行", "人行", "步道", "台阶", "路径", "慢行",
        ),
    ),
    (
        "study_boundary",
        (
            "study area", "study boundary", "research area", "research boundary",
            "研究范围", "研究区", "研究边界",
        ),
    ),
    (
        "area_boundary",
        (
            "neighborhood", "neighbourhood", "district", "administrative",
            "borough", "boundary", "邻里", "街区", "行政", "边界", "分区",
        ),
    ),
)

SEMANTIC_FAMILY_COLORS: Mapping[str, Mapping[str, str]] = {
    "water": {
        "point": "#3F86D1",
        "line": "#2F78BE",
        "polygon": "#5AA1D8",
    },
    "green_space": {
        "point": "#4F925B",
        "line": "#3E7D49",
        "polygon": "#68A96D",
    },
    "parking": {
        "point": "#D8892B",
        "line": "#B66E1F",
        "polygon": "#E2A24D",
    },
    "commercial": {
        "point": "#C45F78",
        "line": "#A84D66",
        "polygon": "#D57B8F",
    },
    "pedestrian": {
        "point": "#167D78",
        "line": "#167D78",
        "polygon": "#55A8A1",
    },
    "study_boundary": {
        "point": "#76654E",
        "line": "#6D5C45",
        "polygon": "#C8B89B",
    },
    "area_boundary": {
        "point": "#738387",
        "line": "#748589",
        "polygon": "#BBC5C7",
    },
}

_SEMANTIC_CATEGORY_PALETTES: Mapping[str, Tuple[str, ...]] = {
    "water": (
        "#2F78BE",  # river / major water
        "#58A5D8",  # stream / canal
        "#8CC4E8",  # pond / lake
        "#3E8FCB",
        "#72B7E1",
        "#A7D5EE",
        "#2569AA",
        "#65ADDA",
    ),
    "pedestrian": (
        "#167D78",  # footway
        "#D07A2D",  # pedestrian zone
        "#8B68A8",  # steps
        "#4D8C57",  # path
        "#397FA6",
        "#B85E69",
        "#8A744B",
        "#61777C",
    ),
    "green_space": (
        "#3E7D49", "#5E9B65", "#83B879", "#2F6D3D",
        "#6EA85E", "#9BC78A", "#4D8650", "#78AE70",
    ),
    "parking": (
        "#D8892B", "#E2A24D", "#B66E1F", "#F0BD73",
        "#C47724", "#E7AE5B", "#9E5D1A", "#F3CA91",
    ),
    "commercial": (
        "#C45F78", "#D57B8F", "#A84D66", "#E09AAB",
        "#B65370", "#CF6E86", "#914158", "#E9B5C0",
    ),
}

_WATER_SUBTYPE_COLORS: Mapping[str, str] = {
    "river": "#2F78BE",
    "河流": "#2F78BE",
    "河道": "#2F78BE",
    "stream": "#58A5D8",
    "creek": "#58A5D8",
    "canal": "#58A5D8",
    "溪流": "#58A5D8",
    "沟渠": "#58A5D8",
    "pond": "#8CC4E8",
    "lake": "#8CC4E8",
    "wetland": "#72B7E1",
    "池塘": "#8CC4E8",
    "湖泊": "#8CC4E8",
    "湿地": "#72B7E1",
}

_PEDESTRIAN_SUBTYPE_COLORS: Mapping[str, str] = {
    "footway": "#167D78",
    "步行道": "#167D78",
    "pedestrian": "#D07A2D",
    "步行街": "#D07A2D",
    "步行区": "#D07A2D",
    "steps": "#8B68A8",
    "台阶": "#8B68A8",
    "path": "#4D8C57",
    "路径": "#4D8C57",
}


def _category_parts(value: Any, fallback_label: str) -> Tuple[str, str]:
    if isinstance(value, Mapping):
        return str(value.get("label", fallback_label)), str(value.get("color", ""))
    return fallback_label, str(value or "")


def _layer_search_text(layer_spec: Mapping[str, Any]) -> str:
    style = layer_spec.get("style", {})
    parts = [
        layer_spec.get("id", ""),
        layer_spec.get("name", ""),
        style.get("legend_title", "") if isinstance(style, Mapping) else "",
    ]
    # Raw field names and category values are deliberately excluded. A general
    # land-use layer may contain a ``parking`` field/class without the whole layer
    # being a parking layer. Semantics are accepted only from explicit layer-facing
    # metadata, then category labels refine colors inside that established role.
    return " ".join(str(value) for value in parts if value is not None).casefold()


def infer_semantic_role(layer_spec: Mapping[str, Any]) -> Optional[str]:
    """Infer a small urban-map semantic role from bilingual layer metadata."""

    text = _layer_search_text(layer_spec)
    for role, keywords in _SEMANTIC_KEYWORDS:
        if any(keyword.casefold() in text for keyword in keywords):
            return role
    return None


def semantic_color(role: Optional[str], family: str, fallback: str) -> str:
    colors = SEMANTIC_FAMILY_COLORS.get(str(role or ""), {})
    return str(colors.get(family, fallback))


def _category_colors(categories: Mapping[str, Any]) -> Tuple[str, ...]:
    return tuple(_category_parts(value, str(key))[1].upper() for key, value in categories.items())


def uses_generated_palette(categories: Mapping[str, Any]) -> bool:
    """Return true only for the exact leading Atlas palette generated by the Skill."""

    colors = _category_colors(categories)
    if not colors or len(colors) > len(CATEGORICAL_PALETTE):
        return False
    expected = tuple(color.upper() for color in CATEGORICAL_PALETTE[: len(colors)])
    return colors == expected or (len(set(colors)) == len(colors) and set(colors) == set(expected))


def _subtype_color(role: str, key: str, label: str, index: int) -> str:
    text = f"{key} {label}".casefold()
    lookup: Mapping[str, str]
    if role == "water":
        lookup = _WATER_SUBTYPE_COLORS
    elif role == "pedestrian":
        lookup = _PEDESTRIAN_SUBTYPE_COLORS
    else:
        lookup = {}
    for keyword, color in lookup.items():
        if keyword.casefold() in text:
            return color
    palette = _SEMANTIC_CATEGORY_PALETTES.get(role)
    if palette:
        return palette[index % len(palette)]
    family = SEMANTIC_FAMILY_COLORS.get(role, {})
    return str(family.get("polygon") or family.get("line") or family.get("point") or CATEGORICAL_PALETTE[index])


def semantic_categories(
    layer_spec: Mapping[str, Any],
    categories: Mapping[str, Any],
    *,
    force_generated_only: bool = True,
) -> Tuple[Dict[str, Any], Optional[str], bool]:
    """Resolve semantic category colors while preserving labels and custom colors.

    By default, colors are replaced only when the input is the exact generic
    palette generated by this project. This protects explicit user design.
    """

    role = infer_semantic_role(layer_spec)
    if role not in _SEMANTIC_CATEGORY_PALETTES:
        return deepcopy(dict(categories)), role, False
    if force_generated_only and not uses_generated_palette(categories):
        return deepcopy(dict(categories)), role, False

    resolved: Dict[str, Any] = {}
    for index, (key, value) in enumerate(categories.items()):
        label, _old_color = _category_parts(value, str(key))
        color = _subtype_color(role, str(key), label, index)
        if isinstance(value, Mapping):
            item = deepcopy(dict(value))
            item["color"] = color
            resolved[str(key)] = item
        else:
            resolved[str(key)] = color
    return resolved, role, True


def auto_category_colors(
    layer_spec: Mapping[str, Any],
    values: Sequence[Any],
) -> Dict[str, str]:
    """Create category colors for a newly initialized spec."""

    role = infer_semantic_role(layer_spec)
    result: Dict[str, str] = {}
    for index, value in enumerate(values):
        key = str(value)
        if role in _SEMANTIC_CATEGORY_PALETTES:
            result[key] = _subtype_color(str(role), key, key, index)
        else:
            result[key] = CATEGORICAL_PALETTE[index]
    return result


__all__ = [
    "CATEGORICAL_PALETTE",
    "SEMANTIC_FAMILY_COLORS",
    "auto_category_colors",
    "infer_semantic_role",
    "semantic_categories",
    "semantic_color",
    "uses_generated_palette",
]
