from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REPLACEMENTS = {
    "README.md": [
        (
            "Shapefile, CSV, Excel, or ArcGIS data, and the Agent inspects the inputs, closes only blocking\nrequirements gaps, writes an auditable MapSpec, builds the appropriate map product, and verifies the\nfinal handoff.",
            "Shapefile, CSV, Excel, or ArcGIS data, and the Agent inspects the inputs, resolves build-critical\nrequirements, writes an auditable MapSpec, builds the appropriate map product, and verifies the final\nhandoff.",
        ),
        (
            "The product stays deliberately map-first: it helps people **find spatial objects, understand them in\ncontext, save important viewpoints, and deliver the result** without turning the browser page into a\ngeneric BI dashboard.",
            "The product stays map-first and focuses on **finding spatial objects, understanding spatial context,\nsaving important viewpoints, and delivering the result** through one interactive map interface.",
        ),
        (
            "- **Search & filter.** Find records by name or attributes, filter categories and numeric ranges,\n  sort results, and inspect feature details without reopening desktop GIS.",
            "- **Search & filter.** Find records by name or attributes, filter categories and numeric ranges,\n  sort results, and inspect feature details directly in the browser.",
        ),
        (
            "- **Saved Views.** Save up to eight named center-and-zoom positions in the current browser, then\n  return to Overview or key sites during exploration and presentation. Saved Views do not change\n  MapSpec or mutate the delivered HTML file.",
            "- **Saved Views.** Save up to eight named center-and-zoom positions in the current browser, then\n  return to Overview or key sites during exploration and presentation. Saved Views use browser-local\n  state and stay separate from MapSpec and the delivered HTML file.",
        ),
        (
            "- **Portable delivery.** Deliver a self-contained `map.html`; generate 16:9 or publication\n  PNG/SVG/PDF outputs only when they are explicitly requested.",
            "- **Portable delivery.** Deliver a self-contained `map.html` and generate 16:9 or publication\n  PNG/SVG/PDF outputs from the same visual plan.",
        ),
        (
            "Both live maps are generated by the repository's deterministic engine from fixed\n[NYC Open Data snapshots](assets/examples/SOURCES.md). They are real outputs, not separate design\nmockups.",
            "Both live maps are generated by the repository's deterministic engine from fixed\n[NYC Open Data snapshots](assets/examples/SOURCES.md). The screenshots and live demos show those\ngenerated product outputs directly.",
        ),
        (
            "A common workflow starts with the whole map, narrows to one or more important sites, and then needs\nto return to those exact map positions during a meeting or review. **Saved Views** completes that\nflow: it records only browser-local Center + Zoom state, keeps a fixed Overview entry, supports\nrename/delete, and remains separate from the map's data and MapSpec contract.",
            "A common workflow starts with the whole map, narrows to one or more important sites, and returns to\nthose exact map positions during a meeting or review. **Saved Views** completes that flow by recording\nbrowser-local Center + Zoom state, keeping a fixed Overview entry, supporting rename/delete, and\nremaining separate from the map's data and MapSpec contract.",
        ),
        ("## Ask for the outcome, not the tool", "## Describe the outcome"),
        (
            "My colleagues do not have ArcGIS. Turn these existing layers into one HTML file and export a 16:9\nfigure for the meeting.",
            "Turn these existing layers into one portable HTML file and export a 16:9 figure for the meeting.",
        ),
        (
            "The user can still invoke `$interactive-map-builder` explicitly, but naming the Skill is not\nrequired for a matching Agent task.",
            "Users can invoke `$interactive-map-builder` explicitly, and natural-language outcome requests also\nactivate the Skill.",
        ),
        (
            "Create a new task after installation. Restart Codex once only when the Skill does not appear.\nStarting with v0.4.3, a repository-copy install can become update-managed automatically only when\nall Release-owned files exactly match the checksum-verified official package.",
            "Create a new task after installation. If the Skill does not appear, restart Codex once.\nStarting with v0.4.3, repository-copy installs whose Release-owned files match the checksum-verified\nofficial package can enter managed updates automatically.",
        ),
        (
            "It asks one consolidated round only for blocking choices such as CRS, template, primary layer,\ncategory meaning, display fields, output formats, and audience locale.",
            "It groups build-critical choices into one confirmation round, including CRS, template, primary\nlayer, category meaning, display fields, output formats, and audience locale.",
        ),
        (
            "`doctor` creates a temporary coordinate table, builds a map without network access, verifies the\npackaged Leaflet resources and output hashes, prints a JSON result, and removes the temporary\nfiles. It does not download basemaps or send usage telemetry. The update command prints structured\nJSON containing the local version, official version when known, source, installation type, and\nstatus. For a cached status-only query, run `interactive-map-builder update --check`.",
            "`doctor` runs an offline verification in a temporary workspace: it creates a coordinate table,\nbuilds a map with the packaged Leaflet resources, verifies output hashes, prints a JSON result, and\nremoves the temporary files. The update command prints structured JSON containing the local version,\nofficial version when known, source, installation type, and status. For a cached status query, run\n`interactive-map-builder update --check`.",
        ),
        (
            "Prefer `interactive-map-builder doctor` after installation. In a source checkout where the console\ncommand is not yet available, use `python scripts/cli.py doctor`. The internal\n`python scripts/map_builder.py --help` command intentionally lists only build commands and\nmust not be used to conclude that the package lacks `doctor`.",
            "Prefer `interactive-map-builder doctor` after installation. In a source checkout where the console\ncommand is not yet available, use `python scripts/cli.py doctor`. The formal doctor entry point is\n`interactive-map-builder doctor`; `python scripts/map_builder.py --help` lists the internal build\ncommands.",
        ),
        (
            "Use one active Codex Skill directory rather than keeping duplicate `.codex` and `.agents` copies.\nA legacy Windows location may be `$HOME\\.agents\\skills`; archive it before using the active Codex directory below.",
            "Keep one active Codex Skill directory. A legacy Windows location may be `$HOME\\.agents\\skills`;\narchive it before using the active Codex directory below.",
        ),
        (
            "The Skill ZIP intentionally excludes demos, screenshots, tests, and CI files. Extract it into an\nAgent Skills directory, run `python -m pip install .`, then run `interactive-map-builder doctor`.",
            "The Skill ZIP focuses on runtime delivery. Demos, screenshots, tests, and CI stay in the full\nrepository. Extract the ZIP into an Agent Skills directory, run `python -m pip install .`, then run\n`interactive-map-builder doctor`.",
        ),
        (
            "The product-facing interactions sit on one deterministic delivery path rather than separate ad hoc\nweb pages:",
            "Product interactions and delivery use one deterministic build path:",
        ),
        (
            "The packaged [JSON Schema](scripts/mapcore/resources/map-spec.schema.json) is the only\nmachine-readable MapSpec contract. Canonical keys use `snake_case`; unsupported fields and schema\nversions are rejected instead of being silently migrated.",
            "The packaged [JSON Schema](scripts/mapcore/resources/map-spec.schema.json) defines the\nmachine-readable MapSpec contract. Canonical keys use `snake_case`, and the schema validates the\nsupported fields and schema versions strictly.",
        ),
        (
            "At the start of a Skill task, the Agent runs `interactive-map-builder update --preflight` from the\nSkill root. This is a cached, check-only request: it reuses a valid result for up to 24 hours, never\nmodifies files, stays silent when the installed version is current, and reports only an available\nupdate or a failed check. Offline access never blocks map construction. Set\n`IMB_DISABLE_AUTO_UPDATE=1` to opt out.",
            "At the start of a Skill task, the Agent runs `interactive-map-builder update --preflight` from the\nSkill root. The command checks release status, reuses a valid result for up to 24 hours, preserves\nthe current installation, and reports new-version or check-status information when relevant. Map\nconstruction remains available offline. Set `IMB_DISABLE_AUTO_UPDATE=1` to disable the check.",
        ),
        (
            "Versions v0.3.2–v0.4.2 do not contain the copy-adoption fix. An already installed unmanaged copy of\none of those versions needs one official v0.4.3 reinstall. Later compatible releases can then be\nadopted and applied automatically.",
            "Version v0.4.3 introduced copy-install adoption. Existing unmanaged v0.3.2–v0.4.2 copies can move\ninto the managed update flow through one official v0.4.3 reinstall, after which compatible releases\ncan be adopted and applied automatically.",
        ),
        (
            "Updates are transactional: after replacing a verified release, the updater reinstalls the engine\nand runs the offline doctor. A failed install or doctor check restores the prior Git commit or the\nprevious manifest-owned files. Confirmed release metadata is preserved when application fails, so\nan Agent cannot silently convert “an update is available” into “no update available.” See\n[the verified update policy](references/update-policy.md).",
            "Updates are transactional: after replacing a verified release, the updater reinstalls the engine\nand runs the offline doctor. Recovery restores the prior Git commit or previous manifest-owned files\nwhen installation or verification does not complete successfully. Confirmed release metadata stays\navailable throughout the recovery flow. See [the verified update policy](references/update-policy.md).",
        ),
        (
            "For a genuinely complex Codex task—multiple independent layers, several unresolved design choices,\nor coordinated HTML/slide/paper outputs—the Agent may suggest Plan mode once as an optional\nconvenience. It continues inspecting immediately whether or not the user switches, and clear\nsingle-layer requests do not receive the suggestion.",
            "For complex Codex tasks—multiple independent layers, several design choices, or coordinated\nHTML/slide/paper outputs—the Agent may suggest Plan mode once as an optional convenience. Data\ninspection continues immediately, while clear single-layer requests move directly into the standard\nworkflow.",
        ),
        (
            "The normal deliverable is a portable local `map.html`. “Share with colleagues” means sending that\nfile, not publishing embedded data on the internet. A public URL is discussed only when explicitly\nrequested, after confirming a hosting target and permission to expose the data. Hosting remains a\nseparate workflow from map construction.",
            "The normal deliverable is a portable local `map.html`, ready to send to colleagues. Public URL\nrequests enter a dedicated deployment flow that confirms the hosting target and data-publication\npermissions. Hosting is handled as a separate delivery workflow alongside local map construction.",
        ),
    ],
    "README.zh-CN.md": [
        (
            "Skill。用户只需要描述想得到什么成果，并提供 GeoJSON、GeoPackage、Shapefile、CSV、Excel 或\nArcGIS 数据；Agent 会检查输入、只补齐真正阻塞构建的信息差、写入可审计的 MapSpec，再由确定性\n引擎生成并验证最终地图成果。",
            "Skill。用户描述想得到的成果，并提供 GeoJSON、GeoPackage、Shapefile、CSV、Excel 或\nArcGIS 数据；Agent 会检查输入、确认构建所需信息、写入可审计的 MapSpec，再由确定性引擎生成并\n验证最终地图成果。",
        ),
        (
            "产品始终以地图为主界面：帮助用户**找到空间对象、理解空间上下文、保存重点视角，并把结果直接\n交付**，而不是把页面继续扩张成通用 BI Dashboard。",
            "产品以地图为主界面，聚焦**找到空间对象、理解空间上下文、保存重点视角和成果交付**，形成\n完整的空间数据探索与汇报体验。",
        ),
        (
            "- **搜索与筛选。** 按名称或属性查找对象，筛选类别和数值范围，排序结果，并查看要素详情；不必\n  为了每个问题重新打开桌面 GIS。",
            "- **搜索与筛选。** 直接在浏览器中按名称或属性查找对象，筛选类别和数值范围，排序结果，并\n  查看要素详情。",
        ),
        (
            "- **图层控制。** 在中性总览和重点图层之间切换，同时独立控制图层显隐、图例和底图，避免把\n  “当前重点浏览谁”和“哪些上下文可见”混成一件事。",
            "- **图层控制。** 在中性总览和重点图层之间切换，图层显隐、图例和底图均可独立控制。",
        ),
        (
            "- **保存视角。** 在当前浏览器中保存最多 8 个命名的 Center + Zoom 位置，在探索和汇报时快速\n  返回“总览”或重点场地。保存视角不修改 MapSpec，也不会回写交付的 HTML 文件。",
            "- **保存视角。** 在当前浏览器中保存最多 8 个命名的 Center + Zoom 位置，在探索和汇报时快速\n  返回“总览”或重点场地。视角保存在浏览器本地状态中，与 MapSpec 和交付 HTML 保持独立。",
        ),
        (
            "- **成果交付。** 默认交付自包含的 `map.html`；只有用户明确需要时，才生成 16:9 汇报图或论文用\n  PNG/SVG/PDF。",
            "- **成果交付。** 支持交付自包含的 `map.html`，并从同一视觉方案生成 16:9 汇报图或论文用\n  PNG/SVG/PDF。",
        ),
        (
            "两个在线地图都由仓库中的确定性引擎根据固定的\n[NYC Open Data 数据快照](assets/examples/SOURCES.md)生成，是实际产品输出，不是另外绘制的设计稿。",
            "两个在线地图均由仓库中的确定性引擎根据固定的\n[NYC Open Data 数据快照](assets/examples/SOURCES.md)生成，直接展示正式产品输出。",
        ),
        (
            "一个常见工作流是：先看完整地图，再逐步聚焦到一个或多个值得讲的地点，最后在会议或汇报中\n需要准确回到这些位置。**保存视角**补上了最后一步：它只记录浏览器本地的 Center + Zoom，保留\n固定“总览”，支持重命名和删除，并与地图数据及 MapSpec 构建契约保持分离。",
            "一个常见工作流是：先看完整地图，再逐步聚焦到一个或多个值得讲的地点，并在会议或汇报中\n快速回到这些位置。**保存视角**记录浏览器本地的 Center + Zoom，提供固定“总览”、重命名和\n删除，并与地图数据及 MapSpec 构建契约保持独立。",
        ),
        ("## 直接描述成果，不必记住工具名称", "## 直接描述你想得到的成果"),
        (
            "同事电脑没有 ArcGIS，请把这些现有图层做成一个 HTML 文件，同时导出一张 16:9 汇报图。",
            "请把这些现有图层做成一个可发送的 HTML 文件，同时导出一张 16:9 汇报图。",
        ),
        (
            "用户仍然可以显式调用 `$interactive-map-builder`，但在任务匹配时不需要知道 Skill 名称。",
            "支持显式调用 `$interactive-map-builder`，自然语言描述成果也能触发 Skill。",
        ),
        (
            "安装完成后新建任务。如果新任务中没有出现该 Skill，再重启一次 Codex。从 v0.4.3 开始，\n`$skill-installer` 产生的仓库复制件只有在所有 Release 管理文件与官方校验包完全一致时，才会\n自动转为可更新安装。",
            "安装完成后新建任务；若 Skill 尚未出现，可重启一次 Codex。从 v0.4.3 开始，Release 管理\n文件与官方校验包一致的 `$skill-installer` 仓库复制件可以自动进入受管更新状态。",
        ),
        (
            "它只会集中询问一次真正影响结果的内容，例如 CRS、模板、主图层、分类含义、展示字段、输出\n格式和地图受众语言。",
            "它会集中确认一次真正影响构建的内容，例如 CRS、模板、主图层、分类含义、展示字段、输出\n格式和地图受众语言。",
        ),
        (
            "`doctor` 会在临时目录中生成一张坐标表，离线完成数据读取、地图构建、Leaflet 资源检查和输出\n哈希验证，返回 JSON 结果后删除临时文件。该命令不会下载底图，也不会发送使用统计。更新命令\n返回结构化 JSON，明确给出本地版本、可确认的官方版本、结果来源、安装类型和状态。仅需缓存状态\n查询时，运行 `interactive-map-builder update --check`。",
            "`doctor` 会在本地临时目录中离线完成数据读取、地图构建、Leaflet 资源检查和输出哈希验证，\n返回 JSON 结果后清理临时文件。更新命令返回结构化 JSON，明确给出本地版本、可确认的官方版本、\n结果来源、安装类型和状态；缓存状态查询可使用 `interactive-map-builder update --check`。",
        ),
        (
            "安装后优先运行 `interactive-map-builder doctor`。若在源码目录中尚未生成该命令，可使用\n`python scripts/cli.py doctor`；`python scripts/map_builder.py --help` 只列出内部构建命令，\n不能据此判断正式安装包缺少 `doctor`。",
            "安装后优先运行 `interactive-map-builder doctor`。若在源码目录中尚未生成该命令，可使用\n`python scripts/cli.py doctor`。正式 doctor 入口为 `interactive-map-builder doctor`，\n`python scripts/map_builder.py --help` 展示内部构建命令。",
        ),
        (
            "Codex 只保留一个活动 Skill 目录，避免 `.codex` 与 `.agents` 同时存在重复副本。\n旧版 Windows 安装位置可能是 `$HOME\\.agents\\skills`；使用下方活动目录前先将其归档。",
            "Codex 保留一个活动 Skill 目录。旧版 Windows 安装位置可能是 `$HOME\\.agents\\skills`；\n使用下方活动目录前先将其归档。",
        ),
        (
            "精简 Skill 包不包含演示数据、截图、测试和 CI 文件。将它解压到 Agent Skills 目录后，运行\n`python -m pip install .`，再运行 `interactive-map-builder doctor`。",
            "精简 Skill 包聚焦运行与交付；演示数据、截图、测试和 CI 保留在完整仓库中。将它解压到\nAgent Skills 目录后，运行 `python -m pip install .`，再运行 `interactive-map-builder doctor`。",
        ),
        (
            "工作流不依赖特定客户端界面：检查数据、维护需求清单、写入当前 MapSpec、使用打包引擎构建、\n验证并交付完整 `dist` 目录。",
            "多种 Agent Skills 客户端可以采用同一套工作流：检查数据、维护需求清单、写入当前 MapSpec、\n使用打包引擎构建、验证并交付完整 `dist` 目录。",
        ),
        (
            "面向用户的交互建立在同一条确定性构建路径之上，而不是每次临时拼一个不同的网页：",
            "面向用户的交互与成果交付统一使用同一条确定性构建路径：",
        ),
        (
            "打包的 [JSON Schema](scripts/mapcore/resources/map-spec.schema.json) 是 MapSpec 唯一的机器契约。\n配置只接受规范的 `snake_case` 字段；不支持的字段和 Schema 版本会被直接拒绝，不会静默迁移。",
            "打包的 [JSON Schema](scripts/mapcore/resources/map-spec.schema.json) 定义 MapSpec 的机器契约。\n配置采用规范的 `snake_case` 字段，Schema 对支持字段与版本进行严格校验。",
        ),
        (
            "每次 Skill 任务开始时，Agent 会从 Skill 根目录运行\n`interactive-map-builder update --preflight`。该命令只检查版本：有效结果最多缓存 24 小时，\n不会修改当前安装；版本已是最新时保持静默，只有发现新版本或检查失败时才提示。断网不会阻塞\n地图制作。设置 `IMB_DISABLE_AUTO_UPDATE=1` 可以关闭更新检查。",
            "每次 Skill 任务开始时，Agent 会从 Skill 根目录运行\n`interactive-map-builder update --preflight`。该命令检查版本状态，有效结果最多缓存 24 小时，并\n保持当前安装原样；发现新版本或检查异常时给出提示。离线环境可继续地图制作，设置\n`IMB_DISABLE_AUTO_UPDATE=1` 可以关闭更新检查。",
        ),
        (
            "安装更新属于独立维护动作。`update --apply` 与兼容保留的 `update --auto --force` 继续执行 Release\n校验、Manifest 校验、精确复制安装接管、本地修改保护、重复目录拒绝、安装后 doctor 和失败回滚，\n普通地图任务不再修改正在运行的 Skill。",
            "安装更新作为独立维护动作执行。`update --apply` 与兼容保留的 `update --auto --force` 提供 Release\n校验、Manifest 校验、精确复制安装接管、本地修改保护、重复目录检查、安装后 doctor 和失败回滚。\n地图制作与安装维护保持分离。",
        ),
        (
            "v0.3.2—v0.4.2 本身尚未包含复制安装接管逻辑。已经安装的无 `.git`、无 Manifest 旧副本需要\n通过官方 v0.4.3 做一次重新安装；此后的兼容版本即可自动更新。",
            "v0.4.3 加入复制安装接管逻辑。已有的 v0.3.2—v0.4.2 无 `.git`、无 Manifest 副本可通过\n官方 v0.4.3 重新安装进入受管更新流程，此后的兼容版本即可自动更新。",
        ),
        (
            "更新采用事务式处理：替换经过校验的版本后会重新安装引擎并运行离线 `doctor`；安装或体检失败\n时，自动恢复此前的 Git 提交或原清单管理的全部文件。应用失败时仍保留已经确认的官方版本、\nRelease 地址和 `update_available=true`，不会再把“存在新版本”静默改写为“没有更新”。完整规则\n见[安全更新策略](references/update-policy.md)。",
            "更新采用事务式处理：替换经过校验的版本后重新安装引擎并运行离线 `doctor`；安装或体检未完成\n时，恢复此前的 Git 提交或原清单管理文件。恢复流程继续保留已确认的官方版本、Release 地址和\n`update_available=true`。完整规则见[安全更新策略](references/update-policy.md)。",
        ),
        (
            "当 Codex 任务确实复杂，例如包含多个独立图层、多个待确认设计选项，或需要协调 HTML、汇报图和\n论文图时，Agent 可以在第一轮用一句话将 Plan mode 作为可选建议。用户不切换也会立即继续检查\n数据；明确的单图层任务不会收到这项提示。",
            "当 Codex 任务较复杂，例如包含多个独立图层、多个设计选项，或需要协调 HTML、汇报图和论文图\n时，Agent 可以在第一轮用一句话将 Plan mode 作为可选建议。数据检查会立即继续，明确的单图层\n任务则直接进入标准工作流。",
        ),
        (
            "正常交付物是可移动、可发送的本地 `map.html`。“发给同事”表示发送文件，不等于把内嵌空间数据\n发布到互联网。只有用户明确提出公开网址时，才会在确认托管平台和数据公开权限后进入独立部署\n流程；公网托管不属于地图构建的默认输出。",
            "正常交付物是可移动、可发送的本地 `map.html`，可以直接发送给同事。公开网址需求会在确认\n托管平台和数据公开权限后进入独立部署流程；公网托管作为单独的成果发布流程处理。",
        ),
    ],
    "scripts/mapcore/resources/locales/en-US.json": [
        (
            "\"hero_body\": \"Turn existing spatial data into searchable, filterable, layer-aware interactive maps, save key views for presentation, and export report or publication figures when needed.\"",
            "\"hero_body\": \"Turn existing spatial data into searchable, filterable, layer-aware interactive maps, save key views for presentation, and export report or publication figures from the same visual plan.\"",
        ),
        (
            "\"capabilities_title\": \"Explore spatial data without rebuilding the map for every question.\"",
            "\"capabilities_title\": \"Explore, focus, and present spatial data through one interactive map.\"",
        ),
        (
            "\"Save up to eight named center-and-zoom views in the browser and return to key sites without rebuilding the map.\"",
            "\"Save up to eight named center-and-zoom views in the browser and jump back to key sites during exploration and presentation.\"",
        ),
        (
            "\"Deliver a self-contained HTML map and generate slide or publication figures only when those outputs are requested.\"",
            "\"Deliver a self-contained HTML map and generate slide or publication figures from the same visual plan.\"",
        ),
        (
            "\"demo_body\": \"Both demos are generated by the repository engine from fixed NYC Open Data snapshots; the landing page embeds the real outputs rather than design mockups.\"",
            "\"demo_body\": \"Both demos are generated by the repository engine from fixed NYC Open Data snapshots and embedded directly as current product outputs.\"",
        ),
        (
            "\"journey_body\": \"Saved Views is part of a presentation workflow, not an isolated button: explore broadly, inspect a site in context, then return to that exact map position when presenting.\"",
            "\"journey_body\": \"Saved Views connects broad exploration, site inspection, and presentation: explore the whole map, inspect a site in context, then return to that exact position while presenting.\"",
        ),
        (
            "\"workflow_body\": \"The Agent handles intent and blocking choices; MapSpec records the contract; the deterministic engine owns data handling, rendering, browser checks, and delivery verification.\"",
            "\"workflow_body\": \"The Agent interprets intent and confirms build-critical choices; MapSpec records the contract; the deterministic engine handles data, rendering, browser checks, and delivery verification.\"",
        ),
        (
            "\"Close only the information gaps the data cannot answer.\"",
            "\"Confirm the build-critical details that remain unresolved after inspection.\"",
        ),
    ],
    "scripts/mapcore/resources/locales/zh-CN.json": [
        (
            "\"在浏览器中保存最多 8 个命名的 Center + Zoom 视角，不必重新制作地图即可返回重点场地。\"",
            "\"在浏览器中保存最多 8 个命名的 Center + Zoom 视角，在探索和汇报中快速返回重点场地。\"",
        ),
        (
            "\"交付自包含的 HTML 地图；只有明确需要时，再生成适合汇报或论文的静态图件。\"",
            "\"交付自包含的 HTML 地图，并支持生成适合汇报或论文的静态图件。\"",
        ),
        (
            "\"demo_title\": \"根据任务选择交互方式，而不是套同一个页面。\"",
            "\"demo_title\": \"两种交互方式对应两类地图任务。\"",
        ),
        (
            "\"demo_body\": \"两个演示都由仓库中的确定性引擎根据固定的 NYC Open Data 快照生成；主页嵌入的是实际产品，而不是另外绘制的设计稿。\"",
            "\"demo_body\": \"两个演示均由仓库中的确定性引擎根据固定的 NYC Open Data 快照生成，主页直接嵌入正式产品输出。\"",
        ),
        (
            "\"journey_body\": \"保存视角不是一个孤立按钮，而是汇报工作流的一部分：先整体探索，再查看场地上下文，最后在汇报时准确返回同一个位置。\"",
            "\"journey_body\": \"保存视角连接整体探索、场地查看与汇报回访：先理解全局，再查看场地上下文，最后在汇报中快速返回同一个位置。\"",
        ),
        (
            "\"workflow_body\": \"Agent 负责理解意图和补齐阻塞信息，MapSpec 记录构建契约，确定性引擎统一负责数据处理、渲染、浏览器检查和交付验证。\"",
            "\"workflow_body\": \"Agent 负责理解意图并确认构建所需信息，MapSpec 记录构建契约，确定性引擎统一负责数据处理、渲染、浏览器检查和交付验证。\"",
        ),
        (
            "\"只补齐数据无法回答的信息差。\"",
            "\"集中确认数据检查后仍需确定的构建信息。\"",
        ),
    ],
}


def main() -> None:
    changed = []
    for relative_path, replacements in REPLACEMENTS.items():
        path = ROOT / relative_path
        text = path.read_text(encoding="utf-8")
        original = text
        for old, new in replacements:
            count = text.count(old)
            if count != 1:
                raise RuntimeError(f"Expected one match in {relative_path}: {old!r}; found {count}")
            text = text.replace(old, new, 1)
        if text != original:
            path.write_text(text, encoding="utf-8")
            changed.append(relative_path)
    print("Updated:", ", ".join(changed))


if __name__ == "__main__":
    main()
